services:
  book-info:
    build:
      context: ./book-info-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/bookstore
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
      - redis
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/bookstore
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - kafka
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  cart:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/bookstore
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  wishlist:
    build:
      context: ./wishlist-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/bookstore
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  payment:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/bookstore
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - kafka
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    mem_limit: 1g
    cpus: 1.0
    networks:
      - bookstore
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres
    mem_limit: 1g
    cpus: 1.0
    networks:
      - bookstore
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    mem_limit: 1g
    cpus: 1.0
    networks:
      - bookstore
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    mem_limit: 512m
    cpus: 0.5
    networks:
      - bookstore
volumes:
  mongo-data:
  postgres-data:
networks:
  bookstore:
    driver: bridge