apiVersion: v1
kind: Service
metadata:
  name: book-info-service
  namespace: bookstore
spec:
  selector:
    app: book-info
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer