apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: bookstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: bookstore-cart:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-dsn
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"