apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: bookstore
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: bookstore
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
  type: ClusterIP