apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: bookstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: bookstore-payment:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-dsn
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: kafka-bootstrap-servers
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"