apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: bookstore
spec:
  selector:
    app: wishlist
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer